Name: product.rpc
ListenOn: 127.0.0.1:9002
Mode: dev
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
DataSource: root:123456@tcp(localhost:43306)/product?parseTime=true
CacheRedis:
  - Host: 127.0.0.1:46379
    Pass: "123456"
    Type: node
BizRedis:
  Host: 127.0.0.1:46379
  Pass: "123456"
  Type: node
